### Get a repo by ID
GET http://localhost:3000/api/repos/repo/R_kgDOL54feZ

### Get all repos
GET http://localhost:3000/api/repos/repo

### Get repo by status "private"
GET http://localhost:3000/api/repos?status=1

### Add repo
POST http://localhost:3000/api/repos/post
Content-Type: application/json

{
    "id": "R_kgDOL54feZ",
    "isPrivate": 1,
    "name": "repoTest",
    "url": "https://github.com/pjroggy/repotest"
}

### Put repo

PUT http://localhost:3000/api/repos/repo/R_kgDOL54feZ
Content-Type: application/json

{
    "id": "R_kgDOL54feZ",
    "isPrivate": 2,
    "name": "updateRepoTest",
    "url": "https://github.com/pjroggy/repotest"
}

### Delete repo
DELETE http://localhost:3000/api/repos/repo/R_kgDOL54feZ

### Get a lang by ID
GET http://localhost:3000/api/langs/1

### Get all langs
GET http://localhost:3000/api/langs

### Get lang by label "langTest"
GET http://localhost:3000/api/langs?label=langTest

### Add lang
POST http://localhost:3000/api/langs
Content-Type: application/json

{
    "id": 9,
    "label": "langTest"
}

### Delete lang
DELETE http://localhost:3000/api/repos/9